/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "var(--color-inverse-surface)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "primary": "var(--color-primary)",
        "secondary-container": "var(--color-secondary-container)",
        "tertiary": "var(--color-tertiary)",
        "surface-container": "var(--color-surface-container)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "error-container": "var(--color-error-container)",
        "on-surface": "var(--color-on-surface)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "secondary": "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "primary-container": "var(--color-primary-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-bright": "var(--color-surface-bright)",
        "on-background": "var(--color-on-background)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-primary": "var(--color-on-primary)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "surface": "var(--color-surface)",
        "outline": "var(--color-outline)",
        "on-error": "var(--color-on-error)",
        "primary-fixed": "var(--color-primary-fixed)",
        "background": "var(--color-background)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "error": "var(--color-error)",
        "surface-dim": "var(--color-surface-dim)",
        "on-error-container": "var(--color-on-error-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "tertiary-container": "var(--color-tertiary-container)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-variant": "var(--color-surface-variant)",
        "inverse-primary": "var(--color-inverse-primary)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "8px",
        "touch-target": "48px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "display-stat": ["Outfit", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-mono": ["Inter", "monospace"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "label-bold": ["14px", { "lineHeight": "20px", "fontWeight": "700" }],
        "display-stat": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
