/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dee3e8",
        "on-tertiary-fixed": "#40000d",
        "primary": "#8ed5ff",
        "secondary-container": "#00a572",
        "tertiary": "#ffbcbf",
        "surface-container": "#1b2024",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-highest": "#303539",
        "on-tertiary-fixed-variant": "#92002a",
        "on-tertiary-container": "#8c0028",
        "error-container": "#93000a",
        "on-surface": "#dee3e8",
        "primary-fixed-dim": "#7bd0ff",
        "secondary-fixed": "#6ffbbe",
        "secondary": "#4edea3",
        "on-secondary": "#003824",
        "inverse-on-surface": "#2c3135",
        "primary-container": "#38bdf8",
        "surface-container-lowest": "#0a0f12",
        "on-primary-container": "#004965",
        "on-primary-fixed": "#001e2c",
        "outline-variant": "#3e484f",
        "surface-container-low": "#171c20",
        "surface-bright": "#343a3e",
        "on-background": "#dee3e8",
        "on-secondary-fixed": "#002113",
        "on-tertiary": "#67001b",
        "on-primary": "#00354a",
        "on-primary-fixed-variant": "#004c69",
        "surface": "#0f1418",
        "outline": "#87929a",
        "on-error": "#690005",
        "primary-fixed": "#c4e7ff",
        "background": "#0f1418",
        "tertiary-fixed": "#ffdadb",
        "on-surface-variant": "#bdc8d1",
        "error": "#ffb4ab",
        "surface-dim": "#0f1418",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb2b7",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-container": "#00311f",
        "surface-container-high": "#252b2e",
        "tertiary-container": "#ff929a",
        "surface-tint": "#7bd0ff",
        "surface-variant": "#303539",
        "inverse-primary": "#00668a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "8px",
        "touch-target": "48px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "display-stat": ["Outfit", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-mono": ["Inter", "monospace"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "label-bold": ["14px", { "lineHeight": "20px", "fontWeight": "700" }],
        "display-stat": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
